config/routes.rb
Rails.application.routes.draw do

  post "json/admin/rayons/get_all" => "admin/rayons#get_all" 
  post "json/get_district" => "json#get_district" 
  post "json/get_subdistrict" => "json#get_subdistrict" 
  post "json/admin/data_info_details/get_all" => "admin/data_info_details#get_all" 
  post "json/admin/monthly_info_summaries/get_data" => "admin/monthly_info_summaries#get_data" 
  post "json/homes/get_data" => "homes#get_data" 

  devise_for :admins

  mount Ckeditor::Engine => '/ckeditor'

  devise_for :users

  resources :mains
  resources :homes
  resources :histories
  resources :data_feedbacks
  resources :data_infos
  resources :articles
  resources :testimonials
  resources :admins do
    collection do
      get :edit_password
    end

    member do
      put :update_password
    end        
  end
  
  resources :my_accounts
  resources :contacts
  resources :user_totals do
    member do
      get :execute
    end
  end
  resources :users do
    collection do
      get :edit_password
    end

    member do
      put :update_password
    end        
  end

  namespace :admin do
    resources :admins
    resources :users do 
      member do
        get :reset_password
        get :send_to_trash
        get :restore
      end

      collection do
        get :trash
      end
    end
    resources :premium_users do 
      member do
        get :reset_password
        get :send_to_trash
        get :restore
      end
      
      collection do
        get :trash
      end
    end
    resources :user_groups do 
      member do
        get :update_status
      end
    end
    resources :controller_models
    resources :action_models
    resources :areas
    resources :articles do
      member do
        get :featured
        get :publish
      end
    end
    resources :testimonials do
      member do
        get :featured
      end
    end
    resources :slideshows do
      member do
        get :featured
      end
    end
    resources :rayons
    resources :data_infos
    resources :data_info_details
    resources :monthly_infos do 
      collection do
        get :upload_invoice_form
        put :upload_invoice
      end
    end
    resources :monthly_info_files
    resources :monthly_info_summaries do
      collection do
        get "export/:id" => "user_levels#export", as: "export"
      end
    end
    resources :jenis_layanans
    resources :jenis_infos
    resources :merk_meters
    resources :type_meters
    resources :data_feedbacks do
      member do 
        get :close
      end
    end
    resources :my_accounts
    resources :kawasans
    resources :master_tarifs
    resources :dayas
    resources :feedback_types
    resources :customer_relations
    resources :customer_relation_types
    resources :officers
    resources :examination_items
    resources :repairs
    resources :examinations
    resources :examination_indicators do
      member do
        get :active
      end
    end
    resources :examinations
    resources :repairs_examination_items
    resources :whats
  end

  get 'admins' => 'admins#index', :as => 'admin_root'
  
  root :to => "mains#index"  
end

app/views/admin/admins/_form.html.erb
<%= form_for([:admin,@admin], :html => {:multipart => true, :class => "form-horizontal"}) do |f| %>
  <% if @admin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin.errors.count, "error") %> prohibited this admin from being saved:</h2>

      <ul>
      <% @admin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :username, :class => "col-sm-3 control-label no-padding-right" %>
    <div class="col-sm-9">
      
      <%= f.text_field :username, :class => "col-xs-10 col-sm-5" %>
    </div>
   </div> 

   <div class="form-group">
    <label class="col-sm-3 control-label no-padding-right" for="form-field-2"> Foto </label>
                        
    <div class="col-sm-3">
      <input type="file" name="admin[avatar]" id="id-input-file-1" />
     </div>
  </div>

   <div class="form-group">
    <%= f.label :email, :class => "col-sm-3 control-label no-padding-right" %>
    <div class="col-sm-9">
      
      <%= f.email_field :email, :class => "col-xs-10 col-sm-5" %>
    </div>
   </div> 

   <% if params[:action] == "new" || params[:action] == "create" %>

     <div class="form-group">
      <%= f.label :password, :class => "col-sm-3 control-label no-padding-right" %>
      <div class="col-sm-9">
        
        <%= f.password_field :password, :class => "col-xs-10 col-sm-5" %>
      </div>
     </div> 

     <div class="form-group">
      <%= f.label :password_confirmation, :class => "col-sm-3 control-label no-padding-right" %>
      <div class="col-sm-9">
        
        <%= f.password_field :password_confirmation, :class => "col-xs-10 col-sm-5" %>
      </div>
     </div> 
  <% end %>

  <div class="form-group">
    <%= f.label :nama_user, :class => "col-sm-3 control-label no-padding-right" %>
    <div class="col-sm-9">
      
      <%= f.text_field :name, :class => "col-xs-10 col-sm-5" %>
    </div>
   </div> 

   <div class="form-group">
    <label class="col-sm-3 control-label no-padding-right" for="selectError">User Group</label>
    <div class="col-sm-9">
      <select class="form-search chosen-select" name="admin[user_group_id]" data-rel="chosen">
        <option>-- Select User Group --</option>
          <% @user_groups.each do |user_group| %>
            <% if user_group.id == @admin.user_group_id %>
              <option value="<%= user_group.id %>" selected><%= user_group.name %></option>
            <% else %>
              <option value="<%= user_group.id %>"><%= user_group.name %></option>
            <% end %>
          <% end %>
        </select>
      </div>
   </div> 

   <div class="form-group">
      <label class="col-sm-3 control-label no-padding-right" for="selectError">Area</label>
      <div class="col-sm-9">
        <select class="selectArea form-search chosen-select" name="admin[area_new_id]" data-rel="chosen">
          <option>-- Select Area --</option>
            <% @areas.each do |area| %>
              <% if area.area_id == @admin.area_new_id %>
                <option value="<%= area.area_id %>" selected><%= area.name %></option>
              <% else %>
                <option value="<%= area.area_id %>"><%= area.name %></option>
              <% end %>
            <% end %>
          </select>
        </div>
    </div> 

    <div class="form-group" id='rayongroup' <%= params[:action] != 'edit' ? 'style="display:none"'.html_safe : '' %> >
        <label class="col-sm-3 control-label no-padding-right" for="selectRayon">Rayon</label>
        <div class="col-sm-9">
          <select class="selectRayon form-search" id="admin_rayon_id" name="admin[rayon_new_id]" > <!-- data-rel="chosen"> -->
            <option value="">-- Select Rayon --</option>
            <% if params[:action] == 'edit' %>
              <% @rayons.each do |rayon| %>
                <% if rayon.rayon_id == @admin.rayon_new_id %>
                  <option value="<%= rayon.rayon_id %>" selected><%= rayon.name %></option>
                <% else %>
                  <option value="<%= rayon.rayon_id %>"><%= rayon.name %></option>
                <% end %>
              <% end %>
            <% end %>
          </select>
        </div>
    </div>

   <div class="form-group">
      <label class="col-sm-3 control-label no-padding-right" for="selectError">Kawasan</label>
      <div class="col-sm-9">
        <select class="selectKawasan form-search chosen-select" name="admin[kawasan_id]" data-rel="chosen">
          <option>-- Select Kawasan --</option>
            <% @kawasans.each do |kawasan| %>
              <% if kawasan.id == @admin.kawasan_id %>
                <option value="<%= kawasan.id %>" selected><%= kawasan.nama_kawasan %></option>
              <% else %>
                <option value="<%= kawasan.id %>"><%= kawasan.nama_kawasan %></option>
              <% end %>
            <% end %>
          </select>
        </div>
    </div> 

    <div class="clearfix form-actions">
        <div class="col-md-offset-3 col-md-9">
            <button class="btn btn-info" type="submit">
                <i class="icon-ok bigger-110"></i>
                Submit
            </button>

            &nbsp; &nbsp; &nbsp;
            <button class="btn" type="reset">
                <i class="icon-undo bigger-110"></i>
                Reset
            </button>

            &nbsp; &nbsp; &nbsp;
            <%= link_to admin_admins_path do %>
              <button class="btn btn-success" type="button">
                  <i class="icon-arrow bigger-110"></i>
                  Back
              </button>
            <% end %>
        </div>
    </div>
<% end %>

app/views/admin/admins/edit.html.erb
<% content_for :js do %>

  <%= javascript_include_tag "ajax/admin" %>

<% end %>

<div class="main-content">
  <div class="breadcrumbs" id="breadcrumbs">
    <script type="text/javascript">
      try{ace.settings.check('breadcrumbs' , 'fixed')}catch(e){}
    </script>

    <ul class="breadcrumb">
      <li>
        <i class="icon-home home-icon"></i>
        <%= link_to "Home", admins_path %>
      </li>
      <li class="active">Form Admin</li>
    </ul><!-- .breadcrumb -->
  </div>

  <div class="page-content">
    <div class="page-header">
      <h1>
        Form Admin
                        <small>
          <i class="icon-double-angle-right"></i>
          edit form
        </small>
      </h1>
    </div><!-- /.page-header -->

    <div class="row">
      <div class="col-xs-12">
        <!-- PAGE CONTENT BEGINS -->

        <div class="row">
          
          <div class="col-xs-12">
                <legend>Edit Admin</legend>
                <%= render "form" %>
            </div>

        </div><!-- /row -->

        <!-- PAGE CONTENT ENDS -->
      </div><!-- /.col -->
    </div><!-- /.row -->
  </div><!-- /.page-content -->
</div><!-- /.main-content -->

app/views/admin/admins/index.html.erb
<%= content_for :js do %>
  <script type="text/javascript">
      jQuery(function($) {
        var oTable1 = $('#sample-table-2').dataTable({"aaSorting": []});
        
        
        $('table th input:checkbox').on('click' , function(){
          var that = this;
          $(this).closest('table').find('tr > td:first-child input:checkbox')
          .each(function(){
            this.checked = that.checked;
            $(this).closest('tr').toggleClass('selected');
          });
            
        });
      
      
        $('[data-rel="tooltip"]').tooltip({placement: tooltip_placement});
        function tooltip_placement(context, source) {
          var $source = $(source);
          var $parent = $source.closest('table')
          var off1 = $parent.offset();
          var w1 = $parent.width();
      
          var off2 = $source.offset();
          var w2 = $source.width();
      
          if( parseInt(off2.left) < parseInt(off1.left) + parseInt(w1 / 2) ) return 'right';
          return 'left';
        }
      })
    </script>
<% end %>

<div class="main-content">
  <div class="breadcrumbs" id="breadcrumbs">
    <script type="text/javascript">
      try{ace.settings.check('breadcrumbs' , 'fixed')}catch(e){}
    </script>

    <ul class="breadcrumb">
      <li>
        <i class="icon-home home-icon"></i>
        <%= link_to "Home", admins_path %>
      </li>
      <li class="active">List Admin</li>
    </ul><!-- .breadcrumb -->
  </div>

  <div class="page-content">
    <div class="page-header">
      <h1>
        Daftar Admin
      </h1>
    </div><!-- /.page-header -->

    <% 
      @not_authorized = true

      if current_admin.user_group
        current_admin.user_group.action_models.each do |action_model|
          if (action_model.controller_model.path == "admin/admins" && action_model.path == "new")
            @not_authorized = false
          end

          break if ! @not_authorized
        end
    end
    %>

    <% if ! @not_authorized || (current_admin.user_group && current_admin.user_group.super == 1) %>

      <%= link_to '<i class="icon-plus icon-white"></i>Create New'.html_safe, new_admin_admin_path, class: "btn btn-info" %>

    <% end %>

    <div class="row">
        <div class="col-xs-12">
        <!-- PAGE CONTENT BEGINS -->
        <div class="table-header">
                      Daftar Admin
                    </div>
        <div class="table-responsive">
                    <table id="sample-table-2" class="table table-striped table-bordered table-hover">
                      <thead>
                        <tr>
                          
                          <th>Nama User</th>
                          <th>User Group</th>
                          <th>Area</th>
                          <th>Rayon</th>
                          <th>Action</th>
                        </tr>
                      </thead>

                      <tbody>
                        <% @admins.each do |admin| %>
                          <tr>
                            

                            <td>
                              <% 
                                  @not_authorized = true

                                  if current_admin.user_group
                                    current_admin.user_group.action_models.each do |action_model|
                                      if (action_model.controller_model.path == "admin/admins" && action_model.path == "show")
                                        @not_authorized = false
                                      end

                                      break if ! @not_authorized
                                    end
                                end
                                %>

                                <% if ! @not_authorized || (current_admin.user_group && current_admin.user_group.super == 1) %>
                                  <%= link_to admin.name, admin_admin_path(admin) %>
                                <% else %>
                                  <%= admin.name %>
                                <% end %>
                            </td>
                            <td><%= admin.user_group ? admin.user_group.name : "N/A" %></td>
                            <td><%= Area.where(:area_id => admin.area_new_id).first ? Area.where(:area_id => admin.area_new_id).first.name : "N/A" %></td>
                            <td><%= Rayon.where(:rayon_id => admin.rayon_new_id).first ? Rayon.where(:rayon_id => admin.rayon_new_id).first.name : "N/A" %></td>

                            <td>
                              <div class="visible-md visible-lg hidden-sm hidden-xs btn-group">
                                <% 
                                  @not_authorized = true

                                  if current_admin.user_group
                                    current_admin.user_group.action_models.each do |action_model|
                                      if (action_model.controller_model.path == "admin/admins" && action_model.path == "edit")
                                        @not_authorized = false
                                      end

                                      break if ! @not_authorized
                                    end
                                end
                                %>

                                <% if ! @not_authorized || (current_admin.user_group && current_admin.user_group.super == 1) %>
                                  <%= link_to edit_admin_admin_path(admin), :class => "btn btn-xs btn-info" do %>
                                    <i class="icon-edit bigger-120"></i>
                                  <% end %>

                                <% end %>

                                <% 
                                  @not_authorized = true

                                  if current_admin.user_group
                                    current_admin.user_group.action_models.each do |action_model|
                                      if (action_model.controller_model.path == "admin/admins" && action_model.path == "destroy")
                                        @not_authorized = false
                                      end

                                      break if ! @not_authorized
                                    end
                                end
                                %>

                                <% if ! @not_authorized || (current_admin.user_group && current_admin.user_group.super == 1) %>

                                  <%= link_to admin_admin_path(admin), :class => "btn btn-xs btn-danger", :rel => "tooltip", :method => :delete, :confirm => "Yakin akan menghapus?" do %>
                                    <i class="icon-trash bigger-120"></i>
                                  <% end %>

                                <% end %>

                                
                              </div>
                            </td>
                          </tr>
                        <% end %>
                      </tbody>
                    </table>
                  </div>

        <!-- PAGE CONTENT ENDS -->
      </div><!-- /.col -->
    </div><!-- /.row -->
  </div><!-- /.page-content -->
</div><!-- /.main-content -->

app/views/admin/admins/new.html.erb
<% content_for :js do %>

  <%= javascript_include_tag "ajax/admin" %>

<% end %>

<div class="main-content">
  <div class="breadcrumbs" id="breadcrumbs">
    <script type="text/javascript">
      try{ace.settings.check('breadcrumbs' , 'fixed')}catch(e){}
    </script>

    <ul class="breadcrumb">
      <li>
        <i class="icon-home home-icon"></i>
        <%= link_to "Home", admins_path %>
      </li>
      <li class="active">Form Admin</li>
    </ul><!-- .breadcrumb -->
  </div>

  <div class="page-content">
    <div class="page-header">
      <h1>
        Form Admin
                        <small>
          <i class="icon-double-angle-right"></i>
          input form
        </small>
      </h1>
    </div><!-- /.page-header -->

    <div class="row">
      <div class="col-xs-12">
        <!-- PAGE CONTENT BEGINS -->

        <div class="row">
          
          <div class="col-xs-12">
                <legend>Input Admin</legend>
                <%= render "form" %>
            </div>

        </div><!-- /row -->

        <!-- PAGE CONTENT ENDS -->
      </div><!-- /.col -->
    </div><!-- /.row -->
  </div><!-- /.page-content -->
</div><!-- /.main-content -->

app/views/admin/admins/show.html.erb
<div class="main-content">
	<div class="breadcrumbs" id="breadcrumbs">
		<script type="text/javascript">
			try{ace.settings.check('breadcrumbs' , 'fixed')}catch(e){}
		</script>

		<ul class="breadcrumb">
			<li>
				<i class="icon-home home-icon"></i>
				<%= link_to "Dashboard", admins_path %>
			</li>
			<li>
				<%= link_to "Admin", admin_admins_path %>
			</li>
			<li class="active"><%= @admin.name %></li>
		</ul><!-- .breadcrumb -->
	</div>

	<div class="page-content">

		<div class="row">
			<div class="col-xs-12">
				<!-- PAGE CONTENT BEGINS -->
				<div class="">
					<div id="user-profile-2" class="user-profile">
						<div class="row">
							<div class="col-xs-12 col-sm-2 center">
								<span class="profile-picture">
									<%= image_tag(@admin.avatar(:medium), :class => "editable img-responsive", :id => "avatar2") %>
								</span>
							</div><!-- /span -->

							<div class="col-xs-12 col-sm-10">
								<h4 class="blue">
									<span class="middle"><%= @admin.name %></span>
								</h4>

								<div class="profile-admin-info profile-user-info-striped">
									<div class="profile-info-row">
										<div class="profile-info-name"> Username </div>

										<div class="profile-info-value">
											<span><%= @admin.username %>&nbsp;</span>
										</div>
									</div>

									<div class="profile-info-row">
										<div class="profile-info-name"> Email </div>

										<div class="profile-info-value">
											<span><%= @admin.email %>&nbsp;</span>
										</div>
									</div>

									<div class="profile-info-row">
										<div class="profile-info-name"> User Group </div>

										<div class="profile-info-value">
											<span><%= @admin.user_group ? @admin.user_group.name : "N/A" %>&nbsp;</span>
										</div>
									</div>

									<div class="profile-info-row">
										<div class="profile-info-name"> Rayon </div>

										<div class="profile-info-value">
											<span><%= Rayon.where(:rayon_id => @admin.rayon_new_id).first ? Rayon.where(:rayon_id => @admin.rayon_new_id).first.name : "N/A" %></span>
										</div>
									</div>

									<div class="profile-info-row">
										<div class="profile-info-name"> Area </div>

										<div class="profile-info-value">
											<span><%= Area.where(:area_id => @admin.area_new_id).first ? Area.where(:area_id => @admin.area_new_id).first.name : "N/A" %></span>
										</div>
									</div>

									<div class="profile-info-row">
										<div class="profile-info-name"> Kawasan </div>

										<div class="profile-info-value">
											<span><%= Kawasan.where(:id => @admin.kawasan_id).first ? Kawasan.where(:id => @admin.kawasan_id).first.nama_kawasan : "N/A" %></span>
										</div>
									</div>
								</div>
			                    </div>
							</div><!-- /span -->
						</div><!-- /row-fluid -->

						<div class="clearfix form-actions">
	                        <div class="col-md-offset-3 col-md-9">
	                        	<% 
							      @not_authorized = true

							      if current_admin.user_group
							        current_admin.user_group.action_models.each do |action_model|
							          if (action_model.controller_model.path == "admin/admins" && action_model.path == "edit")
							            @not_authorized = false
							          end

							          break if ! @not_authorized
							        end
							    end
							    %>

							    <% if ! @not_authorized || (current_admin.user_group && current_admin.user_group.super == 1) %>

		                        	<%= link_to edit_admin_admin_path(@admin) do %>
			                            <button class="btn btn-info" type="button">
			                                <i class="icon-edit bigger-110"></i>
			                                Edit
			                            </button>
			                        <% end %>
			                    <% end %>

			                    <% 
							      @not_authorized = true

							      if current_admin.user_group
							        current_admin.user_group.action_models.each do |action_model|
							          if (action_model.controller_model.path == "admin/admins" && action_model.path == "index")
							            @not_authorized = false
							          end

							          break if ! @not_authorized
							        end
							    end
							    %>

							    <% if ! @not_authorized || (current_admin.user_group && current_admin.user_group.super == 1) %>

		                            &nbsp; &nbsp; &nbsp;
		                            <%= link_to admin_admins_path do %>
		                              <button class="btn btn-success" type="button">
		                                  <i class="icon-arrow bigger-110"></i>
		                                  Back
		                              </button>
		                            <% end %>
		                        <% end %>
	                        </div>
					</div>
				</div>

				

				<!-- PAGE CONTENT ENDS -->
			</div><!-- /.col -->
		</div><!-- /.row -->
	</div><!-- /.page-content -->
</div><!-- /.main-content -->