config/routes.rb
Rails.application.routes.draw do

  post "json/admin/rayons/get_all" => "admin/rayons#get_all" 
  post "json/get_district" => "json#get_district" 
  post "json/get_subdistrict" => "json#get_subdistrict" 
  post "json/admin/data_info_details/get_all" => "admin/data_info_details#get_all" 
  post "json/admin/monthly_info_summaries/get_data" => "admin/monthly_info_summaries#get_data" 
  post "json/homes/get_data" => "homes#get_data" 

  devise_for :admins

  mount Ckeditor::Engine => '/ckeditor'

  devise_for :users

  resources :mains
  resources :homes
  resources :histories
  resources :data_feedbacks
  resources :data_infos
  resources :articles
  resources :testimonials
  resources :admins do
    collection do
      get :edit_password
    end

    member do
      put :update_password
    end        
  end
  
  resources :my_accounts
  resources :contacts
  resources :user_totals do
    member do
      get :execute
    end
  end
  resources :users do
    collection do
      get :edit_password
    end

    member do
      put :update_password
    end        
  end

  namespace :admin do
    resources :admins
    resources :users do 
      member do
        get :reset_password
        get :send_to_trash
        get :restore
      end

      collection do
        get :trash
      end
    end
    resources :premium_users do 
      member do
        get :reset_password
        get :send_to_trash
        get :restore
      end
      
      collection do
        get :trash
      end
    end
    resources :user_groups do 
      member do
        get :update_status
      end
    end
    resources :controller_models
    resources :action_models
    resources :areas
    resources :articles do
      member do
        get :featured
        get :publish
      end
    end
    resources :testimonials do
      member do
        get :featured
      end
    end
    resources :slideshows do
      member do
        get :featured
      end
    end
    resources :rayons
    resources :data_infos
    resources :data_info_details
    resources :monthly_infos do 
      collection do
        get :upload_invoice_form
        put :upload_invoice
      end
    end
    resources :monthly_info_files
    resources :monthly_info_summaries do
      collection do
        get "export/:id" => "user_levels#export", as: "export"
      end
    end
    resources :jenis_layanans
    resources :jenis_infos
    resources :merk_meters
    resources :type_meters
    resources :data_feedbacks do
      member do 
        get :close
      end
    end
    resources :my_accounts
    resources :kawasans
    resources :master_tarifs
    resources :dayas
    resources :feedback_types
    resources :customer_relations
    resources :customer_relation_types
    resources :officers
    resources :examination_items
    resources :repairs
    resources :examinations
    resources :examination_indicators do
      member do
        get :active
      end
    end
    resources :examinations
    resources :repairs_examination_items
    resources :whats
  end

  get 'admins' => 'admins#index', :as => 'admin_root'
  
  root :to => "mains#index"  
end

app/models/examination.rb
class Examination < ActiveRecord::Base
  has_one :repair, :dependent => :destroy
  has_many :examination_examination_items, :dependent => :destroy
  has_many :examination_items, :through => :examination_examination_items
  has_many :examinations_officers
  has_many :officers, :through => :examinations_officers 
  
  belongs_to :user
  belongs_to :examination_indicator
  
  accepts_nested_attributes_for :examination_examination_items, allow_destroy: true
end

app/controllers/admin/examinations_controller.rb
class Admin::ExaminationsController < ApplicationController
  before_filter :authenticate_admin!
  before_filter :authorize_admin
    
  layout "admin"
  
  def index
    @jenis_layanans = JenisLayanan.all
    if current_admin.user_group && current_admin.user_group.super == 1
      @users = User.where("jenis_layanan_id IN (?) AND (flag_status IS NULL OR flag_status = 1)", @jenis_layanans.map(&:id)).order("created_at DESC")
      @areas = Area.order("name ASC")
      @kawasans = Kawasan.order("nama_kawasan ASC")
      @rayons = Rayon.order("name ASC")
      @examinations = Examination.order("created_at DESC")
    elsif current_admin.user_group && current_admin.kawasan
      @kawasan = Kawasan.where(:id => current_admin.kawasan_id).first
      @kawasans = Kawasan.where(:id => current_admin.kawasan_id)
      if @kawasan
        @areas = Area.where("id IS NULL")
        @users = User.where("jenis_layanan_id IN (?) AND kawasan_id = ? AND (flag_status IS NULL OR flag_status = 1)", @jenis_layanans.map(&:id), @kawasan.id).order("created_at DESC")
        @rayons = Rayon.where("id IS NULL")
        @examinations = Examination.where("user_id IN (?)", @users.map(&:id)).order("created_at DESC")
      else
        @users = User.where("id IS NULL") 
        @areas = Area.where("id IS NULL")
        @rayons = Rayon.where("id IS NULL")
        @kawasans = Kawasan.where("id IS NULL")
        @examinations = Examination.where("id IS NULL")
      end
    elsif current_admin.user_group && current_admin.rayon
      @rayon = Rayon.where(:rayon_id => current_admin.rayon_new_id).first
      @rayons = Rayon.where(:rayon_id => current_admin.rayon_new_id)
      if @rayon
        @kawasans = @rayon.area.kawasans.order("nama_kawasan ASC")
        @areas = Area.where("area_id = ?", @rayon.area_new_id)
        @users = User.where("jenis_layanan_id IN (?) AND rayon_new_id = ? AND (flag_status IS NULL OR flag_status = 1)", @jenis_layanans.map(&:id), @rayon.rayon_id).order("created_at DESC")
        @examinations = Examination.where("user_id IN (?)", @users.map(&:id)).order("created_at DESC")
      else
        @users = User.where("id IS NULL") 
        @areas = Area.where("id IS NULL")
        @rayons = Rayon.where("id IS NULL")
        @kawasans = Kawasan.where("id IS NULL")
        @examinations = Examination.where("id IS NULL")
      end
    elsif current_admin.user_group && current_admin.area
      @area = Area.where(:area_id => current_admin.area_new_id).first
      @areas = Area.where(:area_id => current_admin.area_new_id)
      if @area
        @users = User.where("jenis_layanan_id IN (?) AND area_new_id = ? AND (flag_status IS NULL OR flag_status = 1)", @jenis_layanans.map(&:id), @area.area_id).order("created_at DESC")
        @kawasans = @area.kawasans.order("nama_kawasan ASC")
        @rayons = @area.rayons.order("name ASC")
        @examinations = Examination.where("user_id IN (?)", @users.map(&:id)).order("created_at DESC")
      else
        @users = User.where("id IS NULL") 
        @areas = Area.where("id IS NULL")
        @rayons = Rayon.where("id IS NULL")
        @kawasans = Kawasan.where("id IS NULL")
        @examinations = Examination.where("id IS NULL")
      end
    else
      @users = User.where("id IS NULL") 
      @areas = Area.where("id IS NULL")
      @rayons = Rayon.where("id IS NULL")
      @kawasans = Kawasan.where("id IS NULL")
      @examinations = Examination.where("id IS NULL")
    end

    @examination_indicator = ExaminationIndicator.where("status = 1").order("updated_at DESC").first
  end
  
  def new
    @examination_indicator = ExaminationIndicator.where("status = 1").order("updated_at DESC").first
    if !@examination_indicator
      redirect_to admin_examinations_path
    else
       @examination = Examination.new
	     
	     @officers = Officer.order("name ASC")
	     @examination_indicator.examination_items.where("parent_id IS NULL").each do |examination_item|
         @examination.examination_examination_items.build(:examination_item_id => examination_item.id, :condition => 0)
         examination_item.children.each do |child|
            @examination.examination_examination_items.build(:examination_item_id => child.id, :condition => 0)
            child.children.each do |item|
              @examination.examination_examination_items.build(:examination_item_id => item.id, :condition => 0)
           end
         end
       end

       @jenis_layanans = JenisLayanan.where("tipe_jenis_layanan_id = 1")

       if current_admin.user_group && current_admin.user_group.super == 1
          @users = User.where("jenis_layanan_id IN (?) AND (flag_status IS NULL OR flag_status = 1)", @jenis_layanans.map(&:id)).order("created_at DESC")
        elsif current_admin.user_group && current_admin.kawasan
          @kawasan = Kawasan.where(:id => current_admin.kawasan_id).first
          if @kawasan
            @users = User.where("jenis_layanan_id IN (?) AND kawasan_id = ? AND (flag_status IS NULL OR flag_status = 1)", @jenis_layanans.map(&:id), @kawasan.id).order("created_at DESC")
          else
            @users = User.where("id IS NULL") 
          end
        elsif current_admin.user_group && current_admin.rayon
          @rayon = Rayon.where(:rayon_id => current_admin.rayon_new_id).first
          if @rayon
            @users = User.where("jenis_layanan_id IN (?) AND rayon_new_id = ? AND (flag_status IS NULL OR flag_status = 1)", @jenis_layanans.map(&:id), @rayon.rayon_id).order("created_at DESC")
          else
            @users = User.where("id IS NULL")
          end
        elsif current_admin.user_group && current_admin.area
          @area = Area.where(:area_id => current_admin.area_new_id).first
          if @area
            @users = User.where("jenis_layanan_id IN (?) AND area_new_id = ? AND (flag_status IS NULL OR flag_status = 1)", @jenis_layanans.map(&:id), @area.area_id).order("created_at DESC")
          else
            @users = User.where("id IS NULL")
          end
        else
          @users = User.where("id IS NULL")
        end
		
  	   respond_to do |format|
      		format.html # new.html.erb
      		format.xml  { render :xml => @examination }
       end
    end
  end
  
  def show
    @examination = Examination.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.pdf  { render :pdf => "Pemeriksaan", :page_size => 'A4' }
      format.xml  { render :xml => @examination }
    end
  end
  
  def create
    @examination = Examination.new(examination_params)
    @examination_indicator = ExaminationIndicator.where("status = 1").order("updated_at DESC").first

    @jenis_layanans = JenisLayanan.where("tipe_jenis_layanan_id = 1")
    
    if current_admin.user_group && current_admin.user_group.super == 1
      @users = User.where("jenis_layanan_id IN (?) AND (flag_status IS NULL OR flag_status = 1)", @jenis_layanans.map(&:id)).order("created_at DESC")
    elsif current_admin.user_group && current_admin.kawasan
      @kawasan = Kawasan.where(:id => current_admin.kawasan_id).first
      if @kawasan
        @users = User.where("jenis_layanan_id IN (?) AND kawasan_id = ? AND (flag_status IS NULL OR flag_status = 1)", @jenis_layanans.map(&:id), @kawasan.id).order("created_at DESC")
      else
        @users = User.where("id IS NULL") 
      end
    elsif current_admin.user_group && current_admin.rayon
      @rayon = Rayon.where(:rayon_id => current_admin.rayon_new_id).first
      if @rayon
        @users = User.where("jenis_layanan_id IN (?) AND rayon_new_id = ? AND (flag_status IS NULL OR flag_status = 1)", @jenis_layanans.map(&:id), @rayon.rayon_id).order("created_at DESC")
      else
        @users = User.where("id IS NULL")
      end
    elsif current_admin.user_group && current_admin.area
      @area = Area.where(:area_id => current_admin.area_new_id).first
      if @area
        @users = User.where("jenis_layanan_id IN (?) AND area_new_id = ? AND (flag_status IS NULL OR flag_status = 1)", @jenis_layanans.map(&:id), @area.area_id).order("created_at DESC")
      else
        @users = User.where("id IS NULL")
      end
    else
      @users = User.where("id IS NULL")
    end

    @officers = Officer.order("name ASC")
    if params[:datetime_time]
      @examination.examination_time = @examination.examination_time.strftime("%Y-%m-%d") + " " + params[:datetime_time]
    end

    respond_to do |format|
      if @examination.save
      
        examination_examination_items = ExaminationExaminationItem.where(:examination_id => @examination.id , :condition => 3)
        if examination_examination_items.count > 0
          @repair = Repair.new(:user_id => @examination.user_id, :examination_id => @examination.id)
          @repair.save
          examination_examination_items.each do |examination_examination_item|
            @repairs_examination_item = RepairsExaminationItem.new(:repair_id => @repair.id, :examination_item_id => examination_examination_item.examination_item_id)
            @repairs_examination_item.save
          end
        end
        
        format.html { redirect_to(admin_examination_path(@examination), :notice => 'examination was successfully created.') }
        format.xml  { render :xml => @examination, :status => :created, :examination => @examination }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @examination.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  def edit
    @examination = Examination.find(params[:id])
    @examination_indicator = @examination.examination_indicator

    @jenis_layanans = JenisLayanan.where("tipe_jenis_layanan_id = 1")
    
    if current_admin.user_group && current_admin.user_group.super == 1
      @users = User.where("jenis_layanan_id IN (?) AND (flag_status IS NULL OR flag_status = 1)", @jenis_layanans.map(&:id)).order("created_at DESC")
    elsif current_admin.user_group && current_admin.kawasan

app/helpers/admin/examinations_helper.rb
module Admin::ExaminationsHelper
end

app/views/admin/examinations/edit.html.erb
<%= content_for :js do %>
  <%= javascript_include_tag "examination" %>
<% end %>

<div class="main-content">
  <div class="breadcrumbs" id="breadcrumbs">
    <script type="text/javascript">
      try{ace.settings.check('breadcrumbs' , 'fixed')}catch(e){}
    </script>

    <ul class="breadcrumb">
      <li>
        <i class="icon-home home-icon"></i>
        <%= link_to "Home", admins_path %>
      </li>
      <li class="active">Form Pemeriksaan</li>
    </ul><!-- .breadcrumb -->
  </div>

  <div class="page-content">
    <div class="page-header">
      <h1>
        Form Pemeriksaan
                        <small>
          <i class="icon-double-angle-right"></i>
          edit form
        </small>
      </h1>
    </div><!-- /.page-header -->

    <div class="row">
      <div class="col-xs-12">
        <!-- PAGE CONTENT BEGINS -->

        <div class="row">
          
          <div class="col-xs-12">
                <legend>Edit Pemeriksaan</legend>
                <%= render "form" %>
            </div>

        </div><!-- /row -->

        <!-- PAGE CONTENT ENDS -->
      </div><!-- /.col -->
    </div><!-- /.row -->
  </div><!-- /.page-content -->
</div><!-- /.main-content -->

app/views/admin/examinations/index.html.erb
<div class="main-content">
  <div class="breadcrumbs" id="breadcrumbs">
    <script type="text/javascript">
      try{ace.settings.check('breadcrumbs' , 'fixed')}catch(e){}
    </script>

    <ul class="breadcrumb">
      <li>
        <i class="icon-home home-icon"></i>
        <%= link_to "Home", admins_path %>
      </li>
      <li class="active">List Pemeriksaan</li>
    </ul><!-- .breadcrumb -->
  </div>

  <div class="page-content">
    <div class="page-header">
      <h1>
        Daftar Pemeriksaan
      </h1>
    </div><!-- /.page-header -->

    <% if @examination_indicator %>
		<% 
		  @not_authorized = true

		  if current_admin.user_group
			current_admin.user_group.action_models.each do |action_model|
			  if (action_model.controller_model.path == "admin/examinations" && action_model.path == "new")
				@not_authorized = false
			  end

			  break if ! @not_authorized
			end
		end
		%>

		<% if ! @not_authorized || (current_admin.user_group && current_admin.user_group.super == 1) %>

		  <%= link_to '<i class="icon-plus icon-white"></i>Create New'.html_safe, new_admin_examination_path, class: "btn btn-info" %>

		<% end %>
    
    <% end %>

    <div class="row">
        <div class="col-xs-12">
        <!-- PAGE CONTENT BEGINS -->

        <div class="table-responsive">
                    <table id="sample-table-1" class="table table-striped table-bordered table-hover">
                      <thead>
                        <tr>
                          
                          <th>Tanggal</th>
                          <th>Pukul</th>
                          <th>Shift</th>
                          <th>Pelanggan</th>
                          <th>Action</th>
                        </tr>
                      </thead>

                      <tbody>
                        <% @examinations.each do |examination| %>
                          <tr>
                            

                            <td>
							    <% 
                                  @not_authorized = true

                                  if current_admin.user_group
                                    current_admin.user_group.action_models.each do |action_model|
                                      if (action_model.controller_model.path == "admin/examinations" && action_model.path == "show")
                                        @not_authorized = false
                                      end

                                      break if ! @not_authorized
                                    end
                                end
                                %>

                                <% if ! @not_authorized || (current_admin.user_group && current_admin.user_group.super == 1) %>

                                  <%= link_to admin_examination_path(examination) do %>
									<% if examination.examination_time %>
									  <%= examination.examination_time.day %> 
									  <%= @months[examination.examination_time.month] %> 
									  <%= examination.examination_time.year %>
									<% else %>
									  N/A
									<% end %>
                                  <% end %>
                                <% else %>
                                  <% if examination.examination_time %>
									  <%= examination.examination_time.day %> 
									  <%= @months[examination.examination_time.month] %> 
									  <%= examination.examination_time.year %>
									<% else %>
									  N/A
									<% end %>
                                <% end %>
                            </td>
                            <td>
                              <% if examination.examination_time %>
                                <%= sprintf "%02d", examination.examination_time.hour %>:<%= sprintf "%02d", examination.examination_time.min %>
                              <% else %>
                                N/A
                              <% end %>
                            </td>
							<td>
							  <%= examination.shift %>
                            </td>
                            <td>
							  <%= examination.user ? examination.user.idpel+" - "+examination.user.name : "N/A" %>
                            </td>
                            <td>
                              <div class="visible-md visible-lg hidden-sm hidden-xs btn-group">
                                <% 
                                  @not_authorized = true

                                  if current_admin.user_group
                                    current_admin.user_group.action_models.each do |action_model|
                                      if (action_model.controller_model.path == "admin/examinations" && action_model.path == "edit")
                                        @not_authorized = false
                                      end

                                      break if ! @not_authorized
                                    end
                                end
                                %>

                                <% if ! @not_authorized || (current_admin.user_group && current_admin.user_group.super == 1) %>

                                  <%= link_to edit_admin_examination_path(examination), :class => "btn btn-xs btn-warning" do %>
                                    <i class="icon-edit bigger-120"></i>
                                  <% end %>

                                <% end %>

                                <% 
                                  @not_authorized = true

                                  if current_admin.user_group
                                    current_admin.user_group.action_models.each do |action_model|
                                      if (action_model.controller_model.path == "admin/examinations" && action_model.path == "destroy")
                                        @not_authorized = false
                                      end

                                      break if ! @not_authorized
                                    end
                                end
                                %>

                                <% if ! @not_authorized || (current_admin.user_group && current_admin.user_group.super == 1) %>

                                  <%= link_to admin_examination_path(examination), :class => "btn btn-xs btn-danger", :rel => "tooltip", :method => :delete, :confirm => "Yakin akan menghapus?" do %>
                                    <i class="icon-trash bigger-120"></i>
                                  <% end %>
                                <% end %>

                                <a href="/admin/examinations/<%= examination.id %>.pdf" class="btn btn-xs btn-info" target="_blank">
                                    <i class="icon-print bigger-110"></i>
                                </a>
                              </div>
                            </td>
                          </tr>
                        <% end %>
                      </tbody>
                    </table>
                  </div>

        <!-- PAGE CONTENT ENDS -->
      </div><!-- /.col -->
    </div><!-- /.row -->
  </div><!-- /.page-content -->
</div><!-- /.main-content -->

app/views/admin/examinations/new.html.erb
<%= content_for :js do %>
  <%= javascript_include_tag "examination" %>
<% end %>

<div class="main-content">
  <div class="breadcrumbs" id="breadcrumbs">
    <script type="text/javascript">
      try{ace.settings.check('breadcrumbs' , 'fixed')}catch(e){}
    </script>

    <ul class="breadcrumb">
      <li>
        <i class="icon-home home-icon"></i>
        <%= link_to "Home", admins_path %>
      </li>
      <li class="active">Form Pemeriksaan</li>
    </ul><!-- .breadcrumb -->
  </div>

  <div class="page-content">
    <div class="page-header">
      <h1>
        Form Pemeriksaan
                        <small>
          <i class="icon-double-angle-right"></i>
          input form
        </small>
      </h1>
    </div><!-- /.page-header -->

    <div class="row">
      <div class="col-xs-12">
        <!-- PAGE CONTENT BEGINS -->

        <div class="row">
          
          <div class="col-xs-12">
                <legend>Input Pemeriksaan</legend>
                <%= render "form" %>
            </div>

        </div><!-- /row -->

        <!-- PAGE CONTENT ENDS -->
      </div><!-- /.col -->
    </div><!-- /.row -->
  </div><!-- /.page-content -->
</div><!-- /.main-content -->

app/views/admin/examinations/show.html.erb
<div class="main-content">
	<div class="breadcrumbs" id="breadcrumbs">
		<script type="text/javascript">
			try{ace.settings.check('breadcrumbs' , 'fixed')}catch(e){}
		</script>

		<ul class="breadcrumb">
			<li>
				<i class="icon-home home-icon"></i>
				<%= link_to "Home", admins_path %>
			</li>
			<li>
				<%= link_to "Daftar Pemeriksaan", admin_examinations_path %>
			</li>
			<li class="active">Pemeriksaan</li>
		</ul><!-- .breadcrumb -->
	</div>

	<div class="page-content">

		<div class="row">
			<div class="col-xs-12">
				<!-- PAGE CONTENT BEGINS -->
				<div class="">
					<div id="user-profile-2" class="user-profile">
						<div class="row">

							<div class="col-xs-12 col-sm-10">
								<div class="profile-user-info profile-user-info-striped">
									<div class="profile-info-row">
										<div class="profile-info-name"> Tanggal </div>

										<div class="profile-info-value">
											<span><% if @examination.examination_time %>
													  <%= @examination.examination_time.day %> 
													  <%= @months[@examination.examination_time.month] %> 
													  <%= @examination.examination_time.year %>
													<% else %>
													  N/A
													<% end %>&nbsp;</span>
										</div>
									</div>
								</div>
							</div><!-- /span -->

							<div class="col-xs-12 col-sm-10">
								<div class="profile-user-info profile-user-info-striped">
									<div class="profile-info-row">
										<div class="profile-info-name"> Pukul </div>

										<div class="profile-info-value">
											<span><% if @examination.examination_time %><%= sprintf "%02d", @examination.examination_time.hour %>:<%= sprintf "%02d", @examination.examination_time.min %><% else %>N/A<% end %>&nbsp;</span>
										</div>
									</div>
								</div>
							</div><!-- /span -->
							
							<div class="col-xs-12 col-sm-10">
								<div class="profile-user-info profile-user-info-striped">
									<div class="profile-info-row">
										<div class="profile-info-name"> Shift </div>

										<div class="profile-info-value">
											<span><%= @examination.shift %>&nbsp;</span>
										</div>
									</div>
								</div>
							</div><!-- /span -->
							
							<div class="col-xs-12 col-sm-10">
								<div class="profile-user-info profile-user-info-striped">
									<div class="profile-info-row">
										<div class="profile-info-name"> Daftar Petugas </div>

										<div class="profile-info-value">
											<% @examination.officers.each do |officer| %>
												<span><%= officer.name %>&nbsp;</span>
											<% end %>
										</div>
									</div>
								</div>
							</div><!-- /span -->
							
							<div class="col-xs-12 col-sm-10">
								<div class="profile-user-info profile-user-info-striped">
									<div class="profile-info-row">
										<div class="profile-info-name"> Pelanggan </div>

										<div class="profile-info-value">
											<span><%= @examination.user ? @examination.user.idpel+" - "+@examination.user.name : "N/A" %>&nbsp;</span>
										</div>
									</div>
								</div>
							</div><!-- /span -->
							
							<% if @examination.repair %>
							<div class="col-xs-12 col-sm-10">
								<div class="profile-user-info profile-user-info-striped">
									<div class="profile-info-row">
										<div class="profile-info-name"> Perbaikan </div>

										<div class="profile-info-value">
											<% 
											  @not_authorized = true

											  if current_admin.user_group
												current_admin.user_group.action_models.each do |action_model|
												  if (action_model.controller_model.path == "admin/repairs" && action_model.path == "show")
													@not_authorized = false
												  end

												  break if ! @not_authorized
												end
											end
											%>

											<% if ! @not_authorized || (current_admin.user_group && current_admin.user_group.super == 1) %>

											  <%= link_to admin_repair_path(@examination.repair) do %>
												<span>Perbaikan &nbsp;</span>
											  <% end %>
											<% else %>
											    <span>Perbaikan &nbsp;</span>
											<% end %>
										</div>
									</div>
								</div>
							</div><!-- /span -->
							<% end %>
							
						</div><!-- /row-fluid -->
						

						<div class="clearfix form-actions">
	                        <div class="col-md-offset-3 col-md-9">
	                        	<%= link_to edit_admin_examination_path(@examination) do %>
		                            <button class="btn btn-info" type="submit">
		                                <i class="icon-edit bigger-110"></i>
		                                Edit
		                            </button>
		                        <% end %>

	                            &nbsp; &nbsp; &nbsp;
	                            <%= link_to admin_examinations_path do %>
	                              <button class="btn btn-success" type="button">
	                                  <i class="icon-arrow bigger-110"></i>
	                                  Back
	                              </button>
	                            <% end %>

	                            &nbsp; &nbsp; &nbsp;
	                            
          						<a href="/admin/examinations/<%= @examination.id %>.pdf" target="_blank">
	                              <button class="btn btn-danger" type="button">
	                                  <i class="icon-arrow bigger-110"></i>
	                                  Cetak
	                              </button>
	                            </a>
	                        </div>
	                    </div>
					</div>
				</div>

				<div class="table-responsive">
                    <table id="sample-table-1" class="table table-striped table-bordered table-hover">
                      <thead>
                        <tr>
                          
                          <th>Item Pemeriksaan</th>
                          <th>Kondisi</th>
                          <th>Catatan</th>
                        </tr>
                      </thead>

                      <tbody>
                        <% @examination.examination_examination_items.each do |examination_examination_item| %>
                          <tr>
                            

                            <td>
							   <%= examination_examination_item.examination_item.name %>
                            </td>
                            <td>
                              <%= @conditions[examination_examination_item.condition] %>
                            </td>
							<td>
							  <%= examination_examination_item.note %>
                            </td>
                          </tr>
                        <% end %>
                      </tbody>
                    </table>
                  </div>

				<!-- PAGE CONTENT ENDS -->
			</div><!-- /.col -->
		</div><!-- /.row -->
	</div><!-- /.page-content -->
</div><!-- /.main-content -->