config/routes.rb
Rails.application.routes.draw do

  post "json/admin/rayons/get_all" => "admin/rayons#get_all" 
  post "json/get_district" => "json#get_district" 
  post "json/get_subdistrict" => "json#get_subdistrict" 
  post "json/admin/data_info_details/get_all" => "admin/data_info_details#get_all" 
  post "json/admin/monthly_info_summaries/get_data" => "admin/monthly_info_summaries#get_data" 
  post "json/homes/get_data" => "homes#get_data" 

  devise_for :admins

  mount Ckeditor::Engine => '/ckeditor'

  devise_for :users

  resources :mains
  resources :homes
  resources :histories
  resources :data_feedbacks
  resources :data_infos
  resources :articles
  resources :testimonials
  resources :admins do
    collection do
      get :edit_password
    end

    member do
      put :update_password
    end        
  end
  
  resources :my_accounts
  resources :contacts
  resources :user_totals do
    member do
      get :execute
    end
  end
  resources :users do
    collection do
      get :edit_password
    end

    member do
      put :update_password
    end        
  end

  namespace :admin do
    resources :admins
    resources :users do 
      member do
        get :reset_password
        get :send_to_trash
        get :restore
      end

      collection do
        get :trash
      end
    end
    resources :premium_users do 
      member do
        get :reset_password
        get :send_to_trash
        get :restore
      end
      
      collection do
        get :trash
      end
    end
    resources :user_groups do 
      member do
        get :update_status
      end
    end
    resources :controller_models
    resources :action_models
    resources :areas
    resources :articles do
      member do
        get :featured
        get :publish
      end
    end
    resources :testimonials do
      member do
        get :featured
      end
    end
    resources :slideshows do
      member do
        get :featured
      end
    end
    resources :rayons
    resources :data_infos
    resources :data_info_details
    resources :monthly_infos do 
      collection do
        get :upload_invoice_form
        put :upload_invoice
      end
    end
    resources :monthly_info_files
    resources :monthly_info_summaries do
      collection do
        get "export/:id" => "user_levels#export", as: "export"
      end
    end
    resources :jenis_layanans
    resources :jenis_infos
    resources :merk_meters
    resources :type_meters
    resources :data_feedbacks do
      member do 
        get :close
      end
    end
    resources :my_accounts
    resources :kawasans
    resources :master_tarifs
    resources :dayas
    resources :feedback_types
    resources :customer_relations
    resources :customer_relation_types
    resources :officers
    resources :examination_items
    resources :repairs
    resources :examinations
    resources :examination_indicators do
      member do
        get :active
      end
    end
    resources :examinations
    resources :repairs_examination_items
    resources :whats
  end

  get 'admins' => 'admins#index', :as => 'admin_root'
  
  root :to => "mains#index"  
end

app/models/daya.rb
class Daya < ActiveRecord::Base
end

app/controllers/admin/dayas_controller.rb
class Admin::DayasController < ApplicationController
  before_filter :authenticate_admin!
  before_filter :authorize_admin
    
  layout "admin"
  
  def index
    @dayas = Daya.order("name DESC")
  end
  
  def new
    @daya = Daya.new
    
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @daya }
    end
  end
  
  def show
    @daya = Daya.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @daya }
    end
  end
  
  def create
    @daya = Daya.new(daya_params)

    respond_to do |format|
      if @daya.save
        
        format.html { redirect_to(admin_dayas_path, :notice => 'daya was successfully created.') }
        format.xml  { render :xml => @daya, :status => :created, :daya => @daya }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @daya.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  def edit
    @daya = Daya.find(params[:id])
  end
  
  def update
    @daya = Daya.find(params[:id])

    respond_to do |format|
      if @daya.update_attributes(daya_params)
        
        format.html { redirect_to(admin_dayas_path, :notice => 'daya was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @daya.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  def destroy
    @daya = Daya.find(params[:id])
    @daya.destroy

    respond_to do |format|
      format.html { redirect_to(:controller => 'admin/dayas') }
      format.xml  { head :ok }
    end
  end

  private

  def daya_params
    params.require(:daya).permit(:description, :name)
  end
end

app/helpers/admin/dayas_helper.rb
module Admin::DayasHelper
end

app/views/admin/dayas/_form.html.erb
<%= form_for([:admin,@daya], :html => {class:"form-horizontal"}) do |f| %>
  <% if @daya.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@daya.errors.count, "error") %> prohibited this daya from being saved:</h2>

      <ul>
      <% @daya.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="form-group">
    <%= f.label :name, class:"col-sm-3 control-label no-padding-right" %>
    <div class="col-sm-9">
      
      <%= f.text_field :name, :class => "col-xs-10 col-sm-5" %> VA
    </div>
   </div> 

    <div class="clearfix form-actions">
        <div class="col-md-offset-3 col-md-9">
            <button class="btn btn-info" type="submit">
                <i class="icon-ok bigger-110"></i>
                Submit
            </button>

            &nbsp; &nbsp; &nbsp;
            <button class="btn" type="reset">
                <i class="icon-undo bigger-110"></i>
                Reset
            </button>

            &nbsp; &nbsp; &nbsp;
            <%= link_to admin_dayas_path do %>
              <button class="btn btn-success" type="button">
                  <i class="icon-arrow bigger-110"></i>
                  Back
              </button>
            <% end %>
        </div>
    </div>
<% end %>

app/views/admin/dayas/edit.html.erb
<div class="main-content">
  <div class="breadcrumbs" id="breadcrumbs">
    <script type="text/javascript">
      try{ace.settings.check('breadcrumbs' , 'fixed')}catch(e){}
    </script>

    <ul class="breadcrumb">
      <li>
        <i class="icon-home home-icon"></i>
        <%= link_to "Home", admins_path %>
      </li>
      <li class="active">Form Daya</li>
    </ul><!-- .breadcrumb -->
  </div>

  <div class="page-content">
    <div class="page-header">
      <h1>
        Form Daya
                        <small>
          <i class="icon-double-angle-right"></i>
          edit form
        </small>
      </h1>
    </div><!-- /.page-header -->

    <div class="row">
      <div class="col-xs-12">
        <!-- PAGE CONTENT BEGINS -->

        <div class="row">
          
          <div class="col-xs-12">
                <legend>Edit Daya</legend>
                <%= render "form" %>
            </div>

        </div><!-- /row -->

        <!-- PAGE CONTENT ENDS -->
      </div><!-- /.col -->
    </div><!-- /.row -->
  </div><!-- /.page-content -->
</div><!-- /.main-content -->

app/views/admin/dayas/index.html.erb
<div class="main-content">
  <div class="breadcrumbs" id="breadcrumbs">
    <script type="text/javascript">
      try{ace.settings.check('breadcrumbs' , 'fixed')}catch(e){}
    </script>

    <ul class="breadcrumb">
      <li>
        <i class="icon-home home-icon"></i>
        <%= link_to "Home", admins_path %>
      </li>
      <li class="active">List Daya</li>
    </ul><!-- .breadcrumb -->
  </div>

  <div class="page-content">
    <div class="page-header">
      <h1>
        Daftar Daya
      </h1>
    </div><!-- /.page-header -->

  <% 
      @not_authorized = true

      if current_admin.user_group
        current_admin.user_group.action_models.each do |action_model|
          if (action_model.controller_model.path == "admin/dayas" && action_model.path == "new")
            @not_authorized = false
          end

          break if ! @not_authorized
        end
    end
    %>

    <% if ! @not_authorized || (current_admin.user_group && current_admin.user_group.super == 1) %>

      <%= link_to '<i class="icon-plus icon-white"></i>Create New'.html_safe, new_admin_daya_path, class: "btn btn-info" %>

    <% end %>

    <div class="row">
        <div class="col-xs-12">
        <!-- PAGE CONTENT BEGINS -->

        <div class="table-responsive">
                    <table id="sample-table-1" class="table table-striped table-bordered table-hover">
                      <thead>
                        <tr>
                          
                          <th>Nama</th>
                          <th>Action</th>
                        </tr>
                      </thead>

                      <tbody>
                        <% @dayas.each do |daya| %>
                          <tr>
                            

                            <td>
                              <%= number_to_currency daya.name, :unit => "", :delimiter => ".", :precision => 0 %> VA
                            </td>

                            <td>
                              <div class="visible-md visible-lg hidden-sm hidden-xs btn-group">
                                <% 
                                  @not_authorized = true

                                  if current_admin.user_group
                                    current_admin.user_group.action_models.each do |action_model|
                                      if (action_model.controller_model.path == "admin/dayas" && action_model.path == "edit")
                                        @not_authorized = false
                                      end

                                      break if ! @not_authorized
                                    end
                                end
                                %>

                                <% if ! @not_authorized || (current_admin.user_group && current_admin.user_group.super == 1) %>

                                  <%= link_to edit_admin_daya_path(daya), :class => "btn btn-xs btn-info" do %>
                                    <i class="icon-edit bigger-120"></i>
                                  <% end %>

                                <% end %>

                                <% 
                                  @not_authorized = true

                                  if current_admin.user_group
                                    current_admin.user_group.action_models.each do |action_model|
                                      if (action_model.controller_model.path == "admin/dayas" && action_model.path == "destroy")
                                        @not_authorized = false
                                      end

                                      break if ! @not_authorized
                                    end
                                end
                                %>

                                <% if ! @not_authorized || (current_admin.user_group && current_admin.user_group.super == 1) %>

                                  <%= link_to admin_daya_path(daya), :class => "btn btn-xs btn-danger", :rel => "tooltip", :method => :delete, :confirm => "Yakin akan menghapus?" do %>
                                    <i class="icon-trash bigger-120"></i>
                                  <% end %>
                                <% end %>

                                
                              </div>
                            </td>
                          </tr>
                        <% end %>
                      </tbody>
                    </table>
                  </div>

        <!-- PAGE CONTENT ENDS -->
      </div><!-- /.col -->
    </div><!-- /.row -->
  </div><!-- /.page-content -->
</div><!-- /.main-content -->

app/views/admin/dayas/new.html.erb
<div class="main-content">
  <div class="breadcrumbs" id="breadcrumbs">
    <script type="text/javascript">
      try{ace.settings.check('breadcrumbs' , 'fixed')}catch(e){}
    </script>

    <ul class="breadcrumb">
      <li>
        <i class="icon-home home-icon"></i>
        <%= link_to "Home", admins_path %>
      </li>
      <li class="active">Form Daya</li>
    </ul><!-- .breadcrumb -->
  </div>

  <div class="page-content">
    <div class="page-header">
      <h1>
        Form Daya
                        <small>
          <i class="icon-double-angle-right"></i>
          input form
        </small>
      </h1>
    </div><!-- /.page-header -->

    <div class="row">
      <div class="col-xs-12">
        <!-- PAGE CONTENT BEGINS -->

        <div class="row">
          
          <div class="col-xs-12">
                <legend>Input Daya</legend>
                <%= render "form" %>
            </div>

        </div><!-- /row -->

        <!-- PAGE CONTENT ENDS -->
      </div><!-- /.col -->
    </div><!-- /.row -->
  </div><!-- /.page-content -->
</div><!-- /.main-content -->

app/views/admin/dayas/show.html.erb
<div class="main-content">
	<div class="breadcrumbs" id="breadcrumbs">
		<script type="text/javascript">
			try{ace.settings.check('breadcrumbs' , 'fixed')}catch(e){}
		</script>

		<ul class="breadcrumb">
			<li>
				<i class="icon-home home-icon"></i>
				<%= link_to "Home", admins_path %>
			</li>
			<li>
				<%= link_to "Daftar Daya", admin_dayas_path %>
			</li>
			<li class="active"><%= @daya.name %></li>
		</ul><!-- .breadcrumb -->
	</div>

	<div class="page-content">

		<div class="row">
			<div class="col-xs-12">
				<!-- PAGE CONTENT BEGINS -->
				<div class="">
					<div id="user-profile-2" class="user-profile">
						<div class="row">

							<div class="col-xs-12 col-sm-10">
								<div class="profile-user-info profile-user-info-striped">
									<div class="profile-info-row">
										<div class="profile-info-name"> Nama </div>

										<div class="profile-info-value">
											<span><%= number_to_currency @daya.name, :unit => "", :delimiter => ".", :precision => 0 %>&nbsp;VA</span>
										</div>
									</div>
								</div>
							</div><!-- /span -->
						</div><!-- /row-fluid -->
						

						<div class="clearfix form-actions">
	                        <div class="col-md-offset-3 col-md-9">
	                        	<%= link_to edit_admin_daya_path(@daya) do %>
		                            <button class="btn btn-info" type="submit">
		                                <i class="icon-edit bigger-110"></i>
		                                Edit
		                            </button>
		                        <% end %>

	                            &nbsp; &nbsp; &nbsp;
	                            <%= link_to admin_dayas_path do %>
	                              <button class="btn btn-success" type="button">
	                                  <i class="icon-arrow bigger-110"></i>
	                                  Back
	                              </button>
	                            <% end %>
	                        </div>
	                    </div>
					</div>
				</div>

				

				<!-- PAGE CONTENT ENDS -->
			</div><!-- /.col -->
		</div><!-- /.row -->
	</div><!-- /.page-content -->
</div><!-- /.main-content -->

current_admin.kawasan