config/routes.rb
Rails.application.routes.draw do

  post "json/admin/rayons/get_all" => "admin/rayons#get_all" 
  post "json/get_district" => "json#get_district" 
  post "json/get_subdistrict" => "json#get_subdistrict" 
  post "json/admin/data_info_details/get_all" => "admin/data_info_details#get_all" 
  post "json/admin/monthly_info_summaries/get_data" => "admin/monthly_info_summaries#get_data" 
  post "json/homes/get_data" => "homes#get_data" 

  devise_for :admins

  mount Ckeditor::Engine => '/ckeditor'

  devise_for :users

  resources :mains
  resources :homes
  resources :histories
  resources :data_feedbacks
  resources :data_infos
  resources :articles
  resources :testimonials
  resources :admins do
    collection do
      get :edit_password
    end

    member do
      put :update_password
    end        
  end
  
  resources :my_accounts
  resources :contacts
  resources :user_totals do
    member do
      get :execute
    end
  end
  resources :users do
    collection do
      get :edit_password
    end

    member do
      put :update_password
    end        
  end

  namespace :admin do
    resources :admins
    resources :users do 
      member do
        get :reset_password
        get :send_to_trash
        get :restore
      end

      collection do
        get :trash
      end
    end
    resources :premium_users do 
      member do
        get :reset_password
        get :send_to_trash
        get :restore
      end
      
      collection do
        get :trash
      end
    end
    resources :user_groups do 
      member do
        get :update_status
      end
    end
    resources :controller_models
    resources :action_models
    resources :areas
    resources :articles do
      member do
        get :featured
        get :publish
      end
    end
    resources :testimonials do
      member do
        get :featured
      end
    end
    resources :slideshows do
      member do
        get :featured
      end
    end
    resources :rayons
    resources :data_infos
    resources :data_info_details
    resources :monthly_infos do 
      collection do
        get :upload_invoice_form
        put :upload_invoice
      end
    end
    resources :monthly_info_files
    resources :monthly_info_summaries do
      collection do
        get "export/:id" => "user_levels#export", as: "export"
      end
    end
    resources :jenis_layanans
    resources :jenis_infos
    resources :merk_meters
    resources :type_meters
    resources :data_feedbacks do
      member do 
        get :close
      end
    end
    resources :my_accounts
    resources :kawasans
    resources :master_tarifs
    resources :dayas
    resources :feedback_types
    resources :customer_relations
    resources :customer_relation_types
    resources :officers
    resources :examination_items
    resources :repairs
    resources :examinations
    resources :examination_indicators do
      member do
        get :active
      end
    end
    resources :examinations
    resources :repairs_examination_items
    resources :whats
  end

  get 'admins' => 'admins#index', :as => 'admin_root'
  
  root :to => "mains#index"  
end

app/controllers/admin/whats_controller.rb
class Admin::WhatsController < ApplicationController
  before_filter :authenticate_admin!
  before_filter :authorize_admin
    
  layout "admin"
  
  def index
    @body_content = BodyContent.where("title = 'what'").first

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @body_content }
    end
  end
  
  def edit
    @body_content = BodyContent.find(params[:id])
  end
  
  def update
    @body_content = BodyContent.find(params[:id])

    respond_to do |format|
      if @body_content.update_attributes(what_params)
        
        format.html { redirect_to(admin_whats_path, :notice => 'what was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @body_content.errors, :status => :unprocessable_entity }
      end
    end
  end

  private

  def what_params
    params.require(:body_content).permit(:body, :created_by, :title, :updated_by)
  end
end

app/helpers/admin/whats_helper.rb
module Admin::WhatsHelper
end

app/views/admin/whats/_form.html.erb
<%= form_for([:admin,@body_content], :url => admin_what_path(@body_content), :html => {class:"form-horizontal", :multipart => true}) do |f| %>
  <% if @body_content.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@body_content.errors.count, "error") %> prohibited this body_content from being saved:</h2>

      <ul>
      <% @body_content.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if params[:action] == "new" || params[:action] == "create" %>
    <%= f.hidden_field :created_by, :value => current_admin.id %>
  <% else %>
    <%= f.hidden_field :updated_by, :value => current_admin.id %>
    <%= f.hidden_field :title, :value => "what" %>
  <% end %>

   <div class="form-group">
    <label class="col-sm-3 control-label no-padding-right">Isi</label>
    <div class="col-sm-9">
        <%= f.text_area :body, :class => "ckeditor" %>
    </div>
   </div> 

    <div class="clearfix form-actions">
        <div class="col-md-offset-3 col-md-9">
            <button class="btn btn-info" type="submit">
                <i class="icon-ok bigger-110"></i>
                Submit
            </button>

            &nbsp; &nbsp; &nbsp;
            <button class="btn" type="reset">
                <i class="icon-undo bigger-110"></i>
                Reset
            </button>

            &nbsp; &nbsp; &nbsp;
            <%= link_to admin_whats_path do %>
              <button class="btn btn-success" type="button">
                  <i class="icon-arrow bigger-110"></i>
                  Back
              </button>
            <% end %>
        </div>
    </div>
<% end %>

<%= content_for :js do %>

  <%= javascript_include_tag "ckeditor/init" %>
<% end %>

app/views/admin/whats/edit.html.erb
<div class="main-content">
  <div class="breadcrumbs" id="breadcrumbs">
    <script type="text/javascript">
      try{ace.settings.check('breadcrumbs' , 'fixed')}catch(e){}
    </script>

    <ul class="breadcrumb">
      <li>
        <i class="icon-home home-icon"></i>
        <%= link_to "Home", admins_path %>
      </li>
      <li class="active">Form What</li>
    </ul><!-- .breadcrumb -->
  </div>

  <div class="page-content">
    <div class="page-header">
      <h1>
        Form What
                        <small>
          <i class="icon-double-angle-right"></i>
          edit form
        </small>
      </h1>
    </div><!-- /.page-header -->

    <div class="row">
      <div class="col-xs-12">
        <!-- PAGE CONTENT BEGINS -->

        <div class="row">
          
          <div class="col-xs-12">
                <legend>Edit What</legend>
                <%= render "form" %>
            </div>

        </div><!-- /row -->

        <!-- PAGE CONTENT ENDS -->
      </div><!-- /.col -->
    </div><!-- /.row -->
  </div><!-- /.page-content -->
</div><!-- /.main-content -->

app/views/admin/whats/index.html.erb
<div class="main-content">
	<div class="breadcrumbs" id="breadcrumbs">
		<script type="text/javascript">
			try{ace.settings.check('breadcrumbs' , 'fixed')}catch(e){}
		</script>

		<ul class="breadcrumb">
			<li>
				<i class="icon-home home-icon"></i>
				<%= link_to "Home", admins_path %>
			</li>
			<li class="active">Edit What Content</li>
		</ul><!-- .breadcrumb -->
	</div>

	<div class="page-content">

		<div class="row">
			<div class="col-xs-12">
				<!-- PAGE CONTENT BEGINS -->
				<div class="">
					<div id="user-profile-2" class="user-profile">
						<div class="row">
							<div class="col-xs-12 col-sm-2 center">
								<span class="profile-picture">
									
								</span>
							</div><!-- /span -->

							<div class="col-xs-12 col-sm-10">
								<div class="profile-user-info profile-user-info-striped">

									<div class="profile-info-row">
										<div class="profile-info-name"> Body </div>

										<div class="profile-info-value">
											<span><%= raw(@body_content.body) %>&nbsp;</span>
										</div>
									</div>
								</div>
							</div><!-- /span -->
						</div><!-- /row-fluid -->
						

						<div class="clearfix form-actions">
	                        <div class="col-md-offset-3 col-md-9">
	                        	<%= link_to edit_admin_what_path(@body_content) do %>
		                            <button class="btn btn-info" type="submit">
		                                <i class="icon-edit bigger-110"></i>
		                                Edit
		                            </button>
		                        <% end %>

	                            &nbsp; &nbsp; &nbsp;
	                            <%= link_to admin_whats_path do %>
	                              <button class="btn btn-success" type="button">
	                                  <i class="icon-arrow bigger-110"></i>
	                                  Back
	                              </button>
	                            <% end %>
	                        </div>
	                    </div>
					</div>
				</div>

				

				<!-- PAGE CONTENT ENDS -->
			</div><!-- /.col -->
		</div><!-- /.row -->
	</div><!-- /.page-content -->
</div><!-- /.main-content -->

current_admin.kawasan